export const abfalter = {};

abfalter.basicInfo = {
    name: "abfalter.basicInfo.name",
    base: "abfalter.basicInfo.base",
    spec: "abfalter.basicInfo.spec.",
    mult: "abfalter.basicInfo.mult",
    class: "abfalter.basicInfo.class",
    temp: "abfalter.basicInfo.temp.",
    final: "abfalter.basicInfo.final",
    actual: "abfalter.basicInfo.actual",
    mastery: "abfalter.basicInfo.mastery",
    half: "abfalter.basicInfo.half",
    full: "abfalter.basicInfo.full",
    bonus: "abfalter.basicInfo.bonus",
    ability: "abfalter.basicInfo.ability",
    used: "abfalter.basicInfo.used",
    type: "abfalter.basicInfo.type",
    cost: "abfalter.basicInfo.cost",
    spent: "abfalter.basicInfo.spent",
    yes: "abfalter.basicInfo.yes",
    no: "abfalter.basicInfo.no",
    active: "abfalter.basicInfo.active",
    passive: "abfalter.basicInfo.passive",
    level: "abfalter.basicInfo.level",
    description: "abfalter.basicInfo.description",
    action: "abfalter.basicInfo.action",
    difficulty: "abfalter.basicInfo.difficulty",
    effect: "abfalter.basicInfo.effect",
    routine: "abfalter.basicInfo.routine",
    easy: "abfalter.basicInfo.easy",
    average: "abfalter.basicInfo.average",
    difficult: "abfalter.basicInfo.difficult",
    vDifficult: "abfalter.basicInfo.vDifficult",
    absurd: "abfalter.basicInfo.absurd",
    almostImp: "abfalter.basicInfo.almostImp",
    impossible: "abfalter.basicInfo.impossible",
    inhuman: "abfalter.basicInfo.inhuman",
    zen: "abfalter.basicInfo.zen",

}

abfalter.sheet = {
    newItem: "abfalter.sheet.newItem",
    nameItem: "abfalter.sheet.nameItem",
    edit: "abfalter.sheet.edit",
    delete: "abfalter.sheet.delete",
    equip: "abfalter.sheet.equip"
}

abfalter.magicTab = {
    mproj: "abfalter.magicTab.mproj",
    maccu: "abfalter.magicTab.maccu",
    maccua: "abfalter.magicTab.maccua",
    maccur: "abfalter.magicTab.maccur",
    zeon: "abfalter.magicTab.zeon",
    minnate: "abfalter.magicTab.minnate",
    mtheory: "abfalter.magicTab.mtheory",
    imbalance: "abfalter.magicTab.imbalance",
    offensive: "abfalter.magicTab.offensive",
    defensive: "abfalter.magicTab.defensive",
    standard: "abfalter.magicTab.standard",
    frompow: "abfalter.magicTab.frompow",
    regenmult: "abfalter.magicTab.regenmult",
    recoverymult: "abfalter.magicTab.recoverymult",
    finalregen: "abfalter.magicTab.finalregen",
    summoning: "abfalter.magicTab.summoning",
    summon: "abfalter.magicTab.summon",
    control: "abfalter.magicTab.control",
    bind: "abfalter.magicTab.bind",
    banish: "abfalter.magicTab.banish",
    metaMagic: "abfalter.magicTab.metaMagic",
    addMetaMagic: "abfalter.magicTab.addMetaMagic",
    turnMaint: "abfalter.magicTab.turnMaint",
    addTurnMaint: "abfalter.magicTab.addTurnMaint",
    dailyMaint: "abfalter.magicTab.dailyMaint",
    addDailyMaint: "abfalter.magicTab.addDailyMaint",
    spellPath: "abfalter.magicTab.spellPath",
    addSpellPath: "abfalter.magicTab.addSpellPath",
    mLevels: "abfalter.magicTab.mLevels",
    fromInt: "abfalter.magicTab.fromInt",
    spellBook: "abfalter.magicTab.spellBook",
    addSpell: "abfalter.magicTab.addSpell",
    invocation: "abfalter.magicTab.invocation",
    addInvocation: "abfalter.magicTab.addInvocation",
    incarnation: "abfalter.magicTab.incarnation",
    addIncarnation: "abfalter.magicTab.addIncarnation"
}

abfalter.psychicTab = {
    pp: "abfalter.psychicTab.pp",
    ppotential: "abfalter.psychicTab.ppotential",
    pproj: "abfalter.psychicTab.pproj",
    pmodule: "abfalter.psychicTab.pmodule",
    pmoduleText: "abfalter.psychicTab.pmoduleText",
    pmoduleText2: "abfalter.psychicTab.pmoduleText2",
    pdisc: "abfalter.psychicTab.pdisc",
    paddDisc: "abfalter.psychicTab.paddDisc",
    freeppMax: "abfalter.psychicTab.freeppMax",
    freepp: "abfalter.psychicTab.freepp",
    fromWP: "abfalter.psychicTab.fromWP",
    maintMatrix: "abfalter.psychicTab.maintMatrix",
    numOfSlots: "abfalter.psychicTab.numOfSlots",
    totalppSlots: "abfalter.psychicTab.totalppSlots",
    potency: "abfalter.psychicTab.potency",
    addMaintMatrix: "abfalter.psychicTab.addMaintMatrix",
    mentalPatterns: "abfalter.psychicTab.mentalPatterns",
    psychicMatrices: "abfalter.psychicTab.psychicMatrices",
    patternName: "abfalter.psychicTab.patternName",
    totalCost: "abfalter.psychicTab.totalCost",
    cancelled: "abfalter.psychicTab.cancelled",
    addMentalPattern: "abfalter.psychicTab.addMentalPattern",
    addPsychicMatrix: "abfalter.psychicTab.addPsychicMatrix",
    patternInfoB: "abfalter.psychicTab.patternInfoB",
    patternInfoP: "abfalter.psychicTab.patternInfoP",
    maintInfo: "abfalter.psychicTab.maintInfo",
    cancelCost: "abfalter.psychicTab.cancelCost",
    oppPattern: "abfalter.psychicTab.oppPattern",
    maint: "abfalter.psychicTab.maint"

}

abfalter.armoryTab = {
    wearArmor: "abfalter.armoryTab.wearArmor",
    stats: "abfalter.armoryTab.stats",
    armorStats: "abfalter.armoryTab.armorStats",
    armor: "abfalter.armoryTab.armor",
    addArmor: "abfalter.armoryTab.addArmor",
    prof: "abfalter.armoryTab.prof",
    addProf: "abfalter.armoryTab.addProf",
    quality: "abfalter.armoryTab.quality",
    presence: "abfalter.armoryTab.presence",
    fortitude: "abfalter.armoryTab.fortitude",
    requir: "abfalter.armoryTab.requir",
    penalty: "abfalter.armoryTab.penalty",
    cut: "abfalter.armoryTab.cut",
    imp: "abfalter.armoryTab.imp",
    thr: "abfalter.armoryTab.thr",
    heat: "abfalter.armoryTab.heat",
    ele: "abfalter.armoryTab.ele",
    cold: "abfalter.armoryTab.cold",
    ene: "abfalter.armoryTab.ene",
    spirit: "abfalter.armoryTab.spirit",
    addHelmet: "abfalter.armoryTab.addHelmet",
    finalHelmet: "abfalter.armoryTab.finalHelmet",
    finalArmor: "abfalter.armoryTab.finalArmor",
    totalNatPen: "abfalter.armoryTab.totalNatPen",
    totalMovePen: "abfalter.armoryTab.totalMovePen",
    profName: "abfalter.armoryTab.profName",
    starting: "abfalter.armoryTab.starting",
    similar: "abfalter.armoryTab.similar",
    mixedClass: "abfalter.armoryTab.mixedClass",
    diffType: "abfalter.armoryTab.diffType",
    wholeClass:"abfalter.armoryTab.wholeClass",
    archetype: "abfalter.armoryTab.archetype",
    style: "abfalter.armoryTab.style",
    mystical: "abfalter.armoryTab.mystical",
    psychic: "abfalter.armoryTab.psychic",
    other: "abfalter.armoryTab.other",
    cCoin: "abfalter.armoryTab.cCoin",
    sCoin: "abfalter.armoryTab.sCoin",
    gCoin: "abfalter.armoryTab.gCoin",
    addCoin: "abfalter.armoryTab.addCoin",
    quantity: "abfalter.armoryTab.quantity",
    currency: "abfalter.armoryTab.currency",
    inventory: "abfalter.armoryTab.inventory",
    addInventory: "abfalter.armoryTab.addInventory",
    dmgBarrier: "abfalter.armoryTab.dmgBarrier",
    dmgRdc: "abfalter.armoryTab.dmgRdc",
    weapons: "abfalter.armoryTab.weapons",
    addWeapons: "abfalter.armoryTab.addWeapons",
    finalDmg: "abfalter.armoryTab.finalDmg",
    totalPerPen: "abfalter.armoryTab.totalPerPen"
}

abfalter.settingsTab = {
    openRoll: "abfalter.settingsTab.openRoll",
    fumbleRoll: "abfalter.settingsTab.fumbleRoll",
    charOptions: "abfalter.settingsTab.charOptions",
    presenceMod: "abfalter.settingsTab.presenceMod",
    levelMod: "abfalter.settingsTab.levelMod",
}