export const abfalter = {};

abfalter.basicInfo = {
    name: "abfalter.basicInfo.name",
    base: "abfalter.basicInfo.base",
    spec: "abfalter.basicInfo.spec.",
    mult: "abfalter.basicInfo.mult",
    class: "abfalter.basicInfo.class",
    temp: "abfalter.basicInfo.temp.",
    final: "abfalter.basicInfo.final",
    actual: "abfalter.basicInfo.actual",
    mastery: "abfalter.basicInfo.mastery",
    half: "abfalter.basicInfo.half",
    full: "abfalter.basicInfo.full",
    bonus: "abfalter.basicInfo.bonus",
    ability: "abfalter.basicInfo.ability",
    used: "abfalter.basicInfo.used",
    type: "abfalter.basicInfo.type",
    cost: "abfalter.basicInfo.cost"
}

abfalter.sheet = {
    newItem: "abfalter.sheet.newItem",
    edit: "abfalter.sheet.edit",
    delete: "abfalter.sheet.delete",
    equip: "abfalter.sheet.equip"
}

abfalter.magicTab = {
    mproj: "abfalter.magicTab.mproj",
    maccu: "abfalter.magicTab.maccu",
    maccua: "abfalter.magicTab.maccua",
    maccur: "abfalter.magicTab.maccur",
    zeon: "abfalter.magicTab.zeon",
    minnate: "abfalter.magicTab.minnate",
    mtheory: "abfalter.magicTab.mtheory",
    imbalance: "abfalter.magicTab.imbalance",
    offensive: "abfalter.magicTab.offensive",
    defensive: "abfalter.magicTab.defensive",
    standard: "abfalter.magicTab.standard",
    frompow: "abfalter.magicTab.frompow",
    regenmult: "abfalter.magicTab.regenmult",
    recoverymult: "abfalter.magicTab.recoverymult",
    finalregen: "abfalter.magicTab.finalregen",
    summoning: "abfalter.magicTab.summoning",
    summon: "abfalter.magicTab.summon",
    control: "abfalter.magicTab.control",
    bind: "abfalter.magicTab.bind",
    banish: "abfalter.magicTab.banish",
    metaMagic: "abfalter.magicTab.metaMagic",
    addMetaMagic: "abfalter.magicTab.addMetaMagic",
    turnMaint: "abfalter.magicTab.turnMaint",
    addTurnMaint: "abfalter.magicTab.addTurnMaint",
    dailyMaint: "abfalter.magicTab.dailyMaint",
    addDailyMaint: "abfalter.magicTab.addDailyMaint",
    spellPath: "abfalter.magicTab.spellPath",
    addSpellPath: "abfalter.magicTab.addSpellPath",
    mLevels: "abfalter.magicTab.mLevels",
    fromInt: "abfalter.magicTab.fromInt",
    spellBook: "abfalter.magicTab.spellBook",
    addSpell: "abfalter.magicTab.addSpell",
    invocation: "abfalter.magicTab.invocation",
    addInvocation: "abfalter.magicTab.addInvocation",
    incarnation: "abfalter.magicTab.incarnation",
    addIncarnation: "abfalter.magicTab.addIncarnation"
}

abfalter.armoryTab = {
    wearArmor: "abfalter.armoryTab.wearArmor",
    stats: "abfalter.armoryTab.stats",
    armorStats: "abfalter.armoryTab.armorStats",
    armor: "abfalter.armoryTab.armor",
    addArmor: "abfalter.armoryTab.addArmor",
    prof: "abfalter.armoryTab.prof",
    addProf: "abfalter.armoryTab.addProf",
    quality: "abfalter.armoryTab.quality",
    presence: "abfalter.armoryTab.presence",
    fortitude: "abfalter.armoryTab.fortitude",
    requir: "abfalter.armoryTab.requir",
    penalty: "abfalter.armoryTab.penalty",
    cut: "abfalter.armoryTab.cut",
    imp: "abfalter.armoryTab.imp",
    thr: "abfalter.armoryTab.thr",
    heat: "abfalter.armoryTab.heat",
    ele: "abfalter.armoryTab.ele",
    cold: "abfalter.armoryTab.cold",
    ene: "abfalter.armoryTab.ene",
    spirit: "abfalter.armoryTab.spirit",
    addHelmet: "abfalter.armoryTab.addHelmet",
    finalHelmet: "abfalter.armoryTab.finalHelmet",
    finalArmor: "abfalter.armoryTab.finalArmor",
    totalNatPen: "abfalter.armoryTab.totalNatPen",
    totalMovePen: "abfalter.armoryTab.totalMovePen",
    totalArtPowEq: "abfalter.armoryTab.totalArtPowEq",
    otherArt: "abfalter.armoryTab.otherArt",
    profName: "abfalter.armoryTab.profName",
    starting: "abfalter.armoryTab.starting",
    similar: "abfalter.armoryTab.similar",
    mixedClass: "abfalter.armoryTab.mixedClass",
    diffType: "abfalter.armoryTab.diffType",
    wholeClass:"abfalter.armoryTab.wholeClass",
    archetype: "abfalter.armoryTab.archetype",
    style: "abfalter.armoryTab.style",
    mystical: "abfalter.armoryTab.mystical",
    psychic: "abfalter.armoryTab.psychic",
    other: "abfalter.armoryTab.other",
    cCoin: "abfalter.armoryTab.cCoin",
    sCoin: "abfalter.armoryTab.sCoin",
    gCoin: "abfalter.armoryTab.gCoin",
    addCoin: "abfalter.armoryTab.addCoin",
    quantity: "abfalter.armoryTab.quantity",
    currency: "abfalter.armoryTab.currency",
    inventory: "abfalter.armoryTab.inventory",
    addInventory: "abfalter.armoryTab.addInventory",
    dmgBarrier: "abfalter.armoryTab.dmgBarrier",
    dmgRdc: "abfalter.armoryTab.dmgRdc",
    totWeight: "abfalter.armoryTab.totWeight",
    weapons: "abfalter.armoryTab.weapons",
    addWeapons: "abfalter.armoryTab.addWeapons",
    finalDmg: "abfalter.armoryTab.finalDmg"
}